[2020-04-14 22:28:56] main.CRITICAL: The file "C:/xampp/htdocs/magento/pub/media/tmp/catalog/product/a/l/alice_1.1_5.jpg" doesn't exist or not a file {"exception":"[object] (Magento\\Framework\\Exception\\FileSystemException(code: 0): The file \"C:/xampp/htdocs/magento/pub/media/tmp/catalog/product/a/l/alice_1.1_5.jpg\" doesn't exist or not a file at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\Filesystem\\Directory\\Write.php:70)"} []
[2020-04-17 16:57:19] main.CRITICAL: Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\module-email\\Model\\Transport.php:104, Zend_Mail_Transport_Exception(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\zendframework1\\library\\Zend\\Mail\\Transport\\Sendmail.php:111)"} []
[2020-04-19 23:35:00] main.CRITICAL: The path "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972" cannot be renamed into "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\MediaStorage\Model\File\Storage\Response\Interceptor] {"exception":"[object] (RuntimeException(code: 0): The path \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972\" cannot be renamed into \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php\" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\\MediaStorage\\Model\\File\\Storage\\Response\\Interceptor] at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\Code\\Generator.php:115)"} []
[2020-04-19 23:35:00] main.CRITICAL: The path "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972" cannot be renamed into "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\MediaStorage\Model\File\Storage\Response\Interceptor] {"exception":"[object] (RuntimeException(code: 0): The path \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972\" cannot be renamed into \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php\" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\\MediaStorage\\Model\\File\\Storage\\Response\\Interceptor] at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\Code\\Generator.php:115)"} []
[2020-04-19 23:35:00] main.CRITICAL: The path "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972" cannot be renamed into "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\MediaStorage\Model\File\Storage\Response\Interceptor] {"exception":"[object] (RuntimeException(code: 0): The path \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972\" cannot be renamed into \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php\" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\\MediaStorage\\Model\\File\\Storage\\Response\\Interceptor] at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\Code\\Generator.php:115)"} []
[2020-04-19 23:35:00] main.CRITICAL: The path "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972" cannot be renamed into "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\MediaStorage\Model\File\Storage\Response\Interceptor] {"exception":"[object] (RuntimeException(code: 0): The path \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972\" cannot be renamed into \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php\" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.972,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\\MediaStorage\\Model\\File\\Storage\\Response\\Interceptor] at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\Code\\Generator.php:115)"} []
[2020-04-19 23:57:19] main.CRITICAL: The path "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.13844" cannot be renamed into "C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.13844,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\MediaStorage\Model\File\Storage\Response\Interceptor] {"exception":"[object] (RuntimeException(code: 0): The path \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.13844\" cannot be renamed into \"C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php\" Warning!rename(C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php.13844,C:/xampp/htdocs/magento/generated/code/Magento/MediaStorage/Model/File/Storage/Response/Interceptor.php): El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso. (code: 32) in [Magento\\MediaStorage\\Model\\File\\Storage\\Response\\Interceptor] at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\Code\\Generator.php:115)"} []
[2020-04-20 00:00:49] main.CRITICAL: Warning: array_key_exists(): The first argument should be either a string or an integer in C:\xampp\htdocs\magento\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php on line 215 {"exception":"[object] (Exception(code: 0): Warning: array_key_exists(): The first argument should be either a string or an integer in C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\ObjectManager\\Factory\\AbstractFactory.php on line 215 at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\App\\ErrorHandler.php:61)"} []
[2020-04-20 17:03:01] main.ERROR: DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\xampp\htdocs\magento\vendor\pelago\emogrifier\Classes\Emogrifier.php on line 370 {"exception":"[object] (InvalidArgumentException(code: 0): DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php on line 370 at C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php:1532)"} []
[2020-04-20 17:03:03] main.CRITICAL: Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\module-email\\Model\\Transport.php:104, Zend_Mail_Transport_Exception(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\zendframework1\\library\\Zend\\Mail\\Transport\\Sendmail.php:111)"} []
[2020-04-20 17:06:49] main.ERROR: DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\xampp\htdocs\magento\vendor\pelago\emogrifier\Classes\Emogrifier.php on line 370 {"exception":"[object] (InvalidArgumentException(code: 0): DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php on line 370 at C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php:1532)"} []
[2020-04-20 17:06:50] main.CRITICAL: Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\module-email\\Model\\Transport.php:104, Zend_Mail_Transport_Exception(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\zendframework1\\library\\Zend\\Mail\\Transport\\Sendmail.php:111)"} []
[2020-04-20 21:16:18] main.ERROR: DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\xampp\htdocs\magento\vendor\pelago\emogrifier\Classes\Emogrifier.php on line 370 {"exception":"[object] (InvalidArgumentException(code: 0): DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php on line 370 at C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php:1532)"} []
[2020-04-20 21:16:19] main.CRITICAL: Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\module-email\\Model\\Transport.php:104, Zend_Mail_Transport_Exception(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\zendframework1\\library\\Zend\\Mail\\Transport\\Sendmail.php:111)"} []
[2020-04-20 21:32:45] main.ERROR: DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\xampp\htdocs\magento\vendor\pelago\emogrifier\Classes\Emogrifier.php on line 370 {"exception":"[object] (InvalidArgumentException(code: 0): DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php on line 370 at C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php:1532)"} []
[2020-04-21 16:34:32] main.ERROR: DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\xampp\htdocs\magento\vendor\pelago\emogrifier\Classes\Emogrifier.php on line 370 {"exception":"[object] (InvalidArgumentException(code: 0): DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php on line 370 at C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php:1532)"} []
[2020-04-27 16:33:03] main.CRITICAL: Default Product Listing Sort by does not exist in Available Product Listing Sort By. {"exception":"[object] (Magento\\Eav\\Model\\Entity\\Attribute\\Exception(code: 0): Default Product Listing Sort by does not exist in Available Product Listing Sort By. at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\ObjectManager\\Factory\\AbstractFactory.php:111)"} []
[2020-04-27 16:33:25] main.CRITICAL: Default Product Listing Sort by does not exist in Available Product Listing Sort By. {"exception":"[object] (Magento\\Eav\\Model\\Entity\\Attribute\\Exception(code: 0): Default Product Listing Sort by does not exist in Available Product Listing Sort By. at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\ObjectManager\\Factory\\AbstractFactory.php:111)"} []
[2020-05-01 15:57:34] main.ERROR: DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\xampp\htdocs\magento\vendor\pelago\emogrifier\Classes\Emogrifier.php on line 370 {"exception":"[object] (InvalidArgumentException(code: 0): DOMXPath::query(): Invalid expression in selector >> .block-search .action.search[disabled] << in C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php on line 370 at C:\\xampp\\htdocs\\magento\\vendor\\pelago\\emogrifier\\Classes\\Emogrifier.php:1532)"} []
[2020-05-01 15:57:36] main.CRITICAL: Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\module-email\\Model\\Transport.php:104, Zend_Mail_Transport_Exception(code: 0): Unable to send mail. mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() at C:\\xampp\\htdocs\\magento\\vendor\\magento\\zendframework1\\library\\Zend\\Mail\\Transport\\Sendmail.php:111)"} []
[2020-05-02 22:53:30] main.CRITICAL: Unable to serialize value. {"exception":"[object] (InvalidArgumentException(code: 0): Unable to serialize value. at C:\\xampp\\htdocs\\magento\\vendor\\magento\\framework\\Serialize\\Serializer\\Json.php:26)"} []
